#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 3
#define DYNAMIC_KEYMAP_MACRO_COUNT 9

#define VIAL_KEYBOARD_UID {0xB8, 0x21, 0x6C, 0xA4, 0x09, 0x5E, 0xC3, 0x17}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 1, 2 }
#define VIAL_COMBO_ENTRIES 9

#define NO_ACTION_ONESHOT
#define NO_MUSIC_MODE